name: WZ+ Linux
on:
  workflow_dispatch:
  push:
    branches:
      - windows

jobs:
  WZ_Ubuntu-Make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git libsdl2-dev libvorbis-dev libtheora-dev libogg-dev libvorbis-dev libglew-dev
          ls ./dependencies/all
      - name: Build RSDKv4
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WZ+_linux-ubuntu
          path: bin

  WZ_Ubuntu-CMake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git libsdl2-dev libtheora-dev libogg-dev libvorbis-dev libglew-dev
      - name: Build WZ+ Ubuntu
        run: |
          cmake -B build ${{env.GENERAL_FLAGS}} ${{env.GENERAL_LINUX_FLAGS}}
          cmake --build build --parallel
      # tar the executables so that they don't lose exec permissions
      # see: https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss
      - name: Move artifacts
        run: |
          mkdir -p build/RSDKv4
          mkdir artifacts
          mv ./build/RSDKv4* ./artifacts
          tar -czvf linux.tar.gz -C ./artifacts .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WZ+_Ubuntu
          path: linux.tar.gz