name: WZ+ (Linux)
on:
  workflow_dispatch:
    branches:
      - main
env:
  GENERAL_FLAGS: "-DCMAKE_BUILD_TYPE=Release"
  GENERAL_LINUX_FLAGS: "-DCMAKE_CXX_FLAGS='-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0'"

jobs:
  WZ_Ubuntu-Make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git libsdl2-dev libtheora-dev libogg-dev libvorbis-dev libglew-dev libglfw3-dev
          ls ./dependencies/all
      - name: Build WZ+ Ubuntu (Make)
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WZ+ Ubuntu (Make)
          path: bin

  WZ_Ubuntu-CMake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git libsdl2-dev libtheora-dev libogg-dev libvorbis-dev libglfw3-dev libglew-dev
      - name: Build WZ+ Ubuntu (CMake)
        run: |
          cmake -B build ${{env.GENERAL_FLAGS}} ${{env.GENERAL_LINUX_FLAGS}}
          cmake --build build --parallel
      - name: Move artifacts
        run: |
          mkdir artifacts
          mv "./build/WZ+ (CMake)" ./artifacts
          tar -czvf linux.tar.gz -C ./artifacts .
      # tar the executables so that they don't lose exec permissions
      # see: https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WZ+ Ubuntu (CMake)
          path: linux.tar.gz
