name: Build and Install Dependencies

on:
  push:
    branches:
      - windows
      - linux
      - android
      - win-actions
      - linux-actions
      - MainMenuRewrite

jobs:
  v4-windows-x64:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/windows'  # Only run on the windows branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Download dependencies
        run: |
          # Check if directories exist before creating them
          if (-not (Test-Path -Path "./dependencies/windows")) {
              mkdir ./dependencies/windows
          }
          if (-not (Test-Path -Path "./dependencies/all")) {
              mkdir ./dependencies/all
          }

          # Download libogg and libvorbis
          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.5.zip" -OutFile "libogg.zip"
          Expand-Archive -Path libogg.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libogg-1.3.5 libogg

          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.zip" -OutFile "libvorbis.zip"
          Expand-Archive -Path libvorbis.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libvorbis-1.3.7 libvorbis

          # Download GLEW
          Invoke-WebRequest -Uri "https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0-win32.zip" -OutFile "GLEW.zip"
          Expand-Archive -Path GLEW.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/glew-2.2.0 glew

          # Download SDL2
          Invoke-WebRequest -Uri "https://libsdl.org/release/SDL2-devel-2.0.14-VC.zip" -OutFile "SDL2.zip"
          Expand-Archive -Path SDL2.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/SDL2-2.0.14 SDL2

          # Download Theora
          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/theora/libtheora-1.1.1.zip" -OutFile "libtheora.zip"
          Expand-Archive -Path libtheora.zip -DestinationPath ./dependencies/all
          Rename-Item ./dependencies/all/libtheora-1.1.1 libtheora


      - name: Download and Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=E:\1runner\actions-runner\_work\Wood-Zone-Plus-Decompilation\Wood-Zone-Plus-Decompilation" >> $GITHUB_ENV

      - name: Run vcpkg
        run: |
          & "$env:VCPKG_ROOT\vcpkg.exe" install libogg:x64-windows-static-md libvorbis:x64-windows-static-md libtheora:x64-windows-static-md
          & "$env:VCPKG_ROOT\vcpkg.exe" integrate install

      - name: Build RSDKv4
        run: |
          msbuild RSDKv4.sln /p:Configuration=Release /p:Platform=x64 /p:ForceImportBeforeCppTargets="$env:GITHUB_WORKSPACE/props/winactions_x64.props"

      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/x64/Release/*.dll ./artifacts 
          move ./build/x64/Release/*.exe ./artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: v4-windows-x64
          path: artifacts
