name: Build RSDKv4
on:
  push:
    branches:
      - windows  # Only trigger on the windows branch

jobs:
  v4-windows-x64:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Download and Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=$(pwd)" >> $GITHUB_ENV
          echo "$GITHUB_ENV" >> $GITHUB_PATH

      - name: Confirm vcpkg Installation
        run: |
          echo "VCPKG_ROOT is set to: $env:VCPKG_ROOT"
          if (Test-Path "$env:VCPKG_ROOT/vcpkg.exe") {
              Write-Host "vcpkg.exe found."
          } else {
              Write-Error "vcpkg.exe not found at $env:VCPKG_ROOT/vcpkg.exe"
              exit 1
          }

      - name: Install Dependencies with vcpkg
        run: |
          & "$env:VCPKG_ROOT/vcpkg.exe" install libogg:x64-windows-static-md libvorbis:x64-windows-static-md libtheora:x64-windows-static-md
          & "$env:VCPKG_ROOT/vcpkg.exe" integrate install
      
      - name: Build RSDKv4
        run: |
          msbuild RSDKv4.sln /p:Configuration=Release /p:Platform=x64 /p:ForceImportBeforeCppTargets="$env:GITHUB_WORKSPACE/props/winactions_x64.props"
      
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/x64/Release/*.dll ./artifacts 
          move ./build/x64/Release/*.exe ./artifacts
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v4-windows-x64
          path: artifacts
