name: Build and Install Dependencies

on:
  push:
    branches:
      - windows
      - linux
      - android
      - win-actions
      - linux-actions
      - MainMenuRewrite

jobs:
  v4-windows:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Set VCPKG_ROOT
        run: echo "VCPKG_ROOT=E:\1runner\actions-runner\_work\Wood-Zone-Plus-Decompilation\Wood-Zone-Plus-Decompilation\vcpkg" >> $GITHUB_ENV

      - name: List vcpkg directory
        run: |
          ls "$env:VCPKG_ROOT"

      - name: Install dependencies
        run: |
          & "$env:VCPKG_ROOT/vcpkg.exe" install libogg:x64-windows-static-md libvorbis:x64-windows-static-md libtheora:x64-windows-static-md
          & "$env:VCPKG_ROOT/vcpkg.exe" integrate install

      # Additional build steps for x64
      - name: Build x64
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64
          cmake --build . --config Release

      # Move artifacts for x64
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./Release/*.dll ./artifacts 
          move ./Release/*.exe ./artifacts
      
      # Upload x64 artifacts
      - name: Upload x64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v4-windows-x64
          path: artifacts

  WZ_Ubuntu-Make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git libsdl2-dev libvorbis-dev libtheora-dev libogg-dev libglew-dev
      - name: Build RSDKv4
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WZ+_linux-ubuntu
          path: bin
