name: Build RSDKv4
on:
  push:
    branches:
      - windows  # Only trigger on the windows branch

jobs:
  v4-windows-x64:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Download and Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=$(pwd)" >> $GITHUB_ENV
          echo "$VCPKG_ROOT" >> $GITHUB_PATH
      
      - name: Install Dependencies with vcpkg
        run: |
          Start-Process -NoNewWindow -File "$env:VCPKG_ROOT/vcpkg.exe" -ArgumentList "install", "libogg:x64-windows-static-md", "libvorbis:x64-windows-static-md", "libtheora:x64-windows-static-md" -Wait
          Start-Process -NoNewWindow -File "$env:VCPKG_ROOT/vcpkg.exe" -ArgumentList "integrate", "install" -Wait
      
      - name: Build RSDKv4
        run: |
          msbuild RSDKv4.sln /p:Configuration=Release /p:Platform=x64 /p:ForceImportBeforeCppTargets="$env:GITHUB_WORKSPACE/props/winactions_x64.props"
      
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/x64/Release/*.dll ./artifacts 
          move ./build/x64/Release/*.exe ./artifacts
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v4-windows-x64
          path: artifacts
